#!/bin/bash
show_help() {
    show_banner
    echo -e "${CYAN}Commands:${NC}"
    echo "  palladium                Launch interactive menu"
    echo "  palladium launch <name>  Install + start in one command"
    echo "  palladium stack          Install a pre-built stack"
    echo "  palladium install        Install a single service"
    echo "  palladium start <name>   Start a service"
    echo "  palladium stop <name>    Stop a service"
    echo "  palladium status         Show all services"
    echo "  palladium logs <name>    View service logs"
    echo "  palladium remove <name>  Remove a service"
    echo "  palladium list           List installed services"
    echo "  palladium marketplace    Browse the tool catalog"
    echo "  palladium ai             AI toolkit"
    echo "  palladium backup         Backup all services"
    echo "  palladium restore        Restore from backup"
    echo "  palladium cleanup        Free up Docker space"
    echo "  palladium setup-autorun  Copy autorun files to USB root"
    echo ""
    echo -e "${CYAN}Quick Start:${NC}"
    echo "  palladium                # Pick [1] Quick Start"
    echo "  palladium stack starter  # Service stack with database"
    echo "  palladium launch n8n     # Install + start in one go"
    echo ""
    echo -e "${CYAN}Examples:${NC}"
    echo "  palladium launch ollama       # Install + start Ollama"
    echo "  palladium logs ollama         # View its logs"
    echo "  palladium marketplace         # Browse all 50+ tools"
    echo "  palladium setup-autorun       # Enable plug-and-play"
    echo ""
}
